apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.ingress.issuer.server }}
    # Email address used for ACME registration
    email: {{ .Values.ingress.issuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ include "website.fullname" . }}
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
